import { describe, it, expect, beforeAll, beforeEach } from 'vitest';
import request from 'supertest';
import type { Express } from 'express';
import { DatabaseSync } from 'node:sqlite';
import fs from 'fs';
import os from 'os';
import path from 'path';
import crypto from 'crypto';

// ── A Key Form must state the holder's TRUE position ─────────────────────────
// Signing an inaccurate custody statement is worse than not signing one: it
// converts a bookkeeping error into a document somebody attested to. So the
// only thing that matters here is that the numbers on the form match the
// database at the instant the form was made — never a moment before.

const TEST_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'citywide-freshness-'));
process.env.CITYWIDE_DB_DIR = TEST_DIR;
delete process.env.DB_PATH;
process.env.JWT_SECRET = 'test-secret';
process.env.ENCRYPTION_KEY = crypto.randomBytes(32).toString('hex');
process.env.SEED_PASSWORD = 'demo1234';
delete process.env.SMTP_USER;
delete process.env.SMTP_PASS;

const DB_FILE = path.join(TEST_DIR, 'citywide.db');
const HOLDER = 'ZZ Test AM One';
const MAILBOX = 'keys@citywidekeys.com';

let app: Express;
let token: string;
let db: DatabaseSync;
let keyForm: typeof import('../src/lib/keyForm');
let clientA: number;
let clientB: number;

const auth = (r: request.Test) => r.set('Authorization', `Bearer ${token}`);
const obj = (r: any) => (r ? Object.assign({}, r) : null);
const one = (sql: string, ...p: any[]) => obj(db.prepare(sql).get(...p));

/** What the holder ACTUALLY has out, straight from the custody records. */
const liveTotal = () => keyForm.snapshotHolder(HOLDER).reduce((n, l) => n + l.subtotal, 0);

/** The most recently generated form for this holder. */
const lastForm = () => one(
  'SELECT * FROM key_form_docs WHERE holder_name = ? ORDER BY id DESC LIMIT 1', HOLDER,
);

const scopeOf = (row: any) => JSON.parse(row.scope_json).lines as any[];

/** The holder's STANDING position from the client grid, with no check-outs. */
const gridTotal = () => keyForm.snapshotHolder(HOLDER)
  .reduce((n, l) => n + l.assigned, 0);

beforeAll(async () => {
  app = (await import('../src/index')).default;
  (await import('../src/lib/autoSeed')).autoSeedIfEmpty();
  keyForm = await import('../src/lib/keyForm');
  const login = await request(app).post('/api/auth/login')
    .send({ email: 'cara@citywideboston.com', password: 'demo1234' });
  token = login.body.token;
  db = new DatabaseSync(DB_FILE);
  clientA = one("SELECT id FROM accounts WHERE bc_client_number='09999900001'").id;
  clientB = one("SELECT id FROM accounts WHERE bc_client_number='09999900003'").id;
});

beforeEach(() => {
  db.exec('DELETE FROM key_assignments');
  db.exec('DELETE FROM key_form_docs');
  db.exec('DELETE FROM audit_log');
});

const checkout = (accountId: number, qty: number, type = 'metal') =>
  auth(request(app).post('/api/assignments/checkout')).send({
    account_id: accountId, holder: HOLDER, holder_email: MAILBOX,
    holder_type: 'employee', keys: [{ type, qty }], sign_mode: 'in_person',
  });

const checkin = (accountId: number, qty: number, type = 'metal') =>
  auth(request(app).post('/api/assignments/checkin')).send({
    holder: HOLDER, holder_email: MAILBOX, holder_type: 'employee',
    account_id: accountId, keys: [{ type, qty }],
    condition_on_return: 'good', sign_mode: 'in_person',
  });

describe('§4 THE SCENARIO — a form tracks live state', () => {
  it('check out 2 → the form includes them; check in 1 → the next shows one fewer', async () => {
    // 1. Starting position. NOT zero: the fixtures give AM One a standing
    //    holder-grid position, which is exactly what the form used to miss.
    const before = liveTotal();
    expect(before).toBeGreaterThan(0);
    // eslint-disable-next-line no-console
    console.log(`  §4 step 1 — starting total: ${before} keys across ${keyForm.snapshotHolder(HOLDER).length} client(s)`);

    // 2. Two more keys.
    const out = await checkout(clientA, 2);
    expect(out.status).toBe(201);
    const afterCheckout = liveTotal();
    expect(afterCheckout).toBe(before + 2);
    // eslint-disable-next-line no-console
    console.log(`  §4 step 2 — after checking out 2: ${afterCheckout}`);

    // 3. The form generated by that check-out must already include them.
    const f1 = lastForm();
    expect(f1.total_keys).toBe(afterCheckout);
    expect(scopeOf(f1).reduce((n, l) => n + l.subtotal, 0)).toBe(afterCheckout);
    // eslint-disable-next-line no-console
    console.log(`  §4 step 3 — form ${f1.form_no} total_keys: ${f1.total_keys}`);

    // 4. One comes back.
    const back = await checkin(clientA, 1);
    expect(back.status).toBe(200);
    const afterCheckin = liveTotal();
    expect(afterCheckin).toBe(afterCheckout - 1);

    // 5. The next form shows one fewer.
    const f2 = lastForm();
    expect(f2.id).not.toBe(f1.id);
    expect(f2.total_keys).toBe(afterCheckin);
    expect(f2.total_keys).toBe(f1.total_keys - 1);
    // eslint-disable-next-line no-console
    console.log(`  §4 step 4 — after checking in 1: ${afterCheckin}`);
    // eslint-disable-next-line no-console
    console.log(`  §4 step 5 — form ${f2.form_no} total_keys: ${f2.total_keys} (was ${f1.total_keys})`);
  });

  it('an on-demand form matches the live total exactly', async () => {
    await checkout(clientA, 3);
    await checkout(clientB, 1, 'card');
    const res = await auth(request(app).post('/api/key-forms/generate'))
      .send({ holder: HOLDER, holder_type: 'employee' });
    expect(res.status).toBe(201);
    expect(res.body.forms[0].total_keys).toBe(liveTotal());
    expect(res.body.forms[0].clients_covered).toBe(keyForm.snapshotHolder(HOLDER).length);
  });
});

describe('§1 WHERE THE NUMBERS COME FROM', () => {
  it('the form is written AFTER the custody row lands, never before', async () => {
    await checkout(clientA, 2);
    const form = lastForm();
    const assignment = one(
      "SELECT id FROM key_assignments WHERE assignee = ? ORDER BY id DESC LIMIT 1", HOLDER,
    );
    // The form's source_ref points at a row that already exists — a form built
    // before the commit could not name it.
    expect(form.source_ref).toBe(String(assignment.id));
    expect(form.total_keys).toBe(liveTotal());
  });

  it('ignores holder totals supplied by the caller — it recomputes', async () => {
    await checkout(clientA, 2);
    // A frontend sending a stale or hostile total must not be able to write it
    // onto a document somebody signs.
    const res = await auth(request(app).post('/api/key-forms/generate')).send({
      holder: HOLDER, holder_type: 'employee',
      total_keys: 999, clients_covered: 42,
      lines: [{ client: 'MADE UP', subtotal: 999, metal: 999, card: 0, fob: 0, dispenser: 0, office: 0 }],
    });
    expect(res.status).toBe(201);
    expect(res.body.forms[0].total_keys).toBe(liveTotal());
    expect(JSON.stringify(res.body.forms[0].clients)).not.toContain('MADE UP');
    expect(res.body.forms[0].total_keys).not.toBe(999);
  });

  it('a transfer form states the position AFTER the transfer commits', async () => {
    await checkout(clientA, 2);
    db.prepare("INSERT INTO staff_managers (name, manager_type, role_category, email, active) VALUES ('Freshness Target','ccm','manager','ft@citywideboston.com',1)").run();

    const res = await auth(request(app).post('/api/assignments/transfer')).send({
      account_id: clientA, mode: 'keys',
      from_holder: HOLDER, to_holder: 'Freshness Target',
      to_holder_type: 'employee', to_holder_email: 'ft@citywideboston.com',
      keys: [{ type: 'metal', qty: 2 }], sign_mode: 'in_person',
    });
    expect(res.status).toBe(201);

    // The person who handed them over is left with their standing grid
    // position only — the transfer moved checked-out keys, not the AM
    // attribution on the client row.
    const fromForm = one(
      "SELECT * FROM key_form_docs WHERE holder_name = ? AND event_type='transfer' ORDER BY id DESC LIMIT 1", HOLDER,
    );
    expect(fromForm.total_keys).toBe(gridTotal());
    expect(scopeOf(fromForm).reduce((n, l) => n + l.checked_out, 0)).toBe(0);
    // …and the person who took them holds two.
    const toForm = one(
      "SELECT * FROM key_form_docs WHERE holder_name = 'Freshness Target' ORDER BY id DESC LIMIT 1",
    );
    expect(toForm.total_keys).toBe(2);
  });

  it('excludes keys at ARCHIVED clients from the holder position', async () => {
    await checkout(clientA, 2);
    await checkout(clientB, 1);
    const both = liveTotal();
    const atB = keyForm.snapshotHolder(HOLDER).find((l) => l.account_id === clientB)!.subtotal;
    expect(atB).toBeGreaterThan(0);

    // A site that is no longer live should not inflate what someone is said
    // to be holding on a document they sign — and that covers BOTH the grid
    // attribution and the open check-out there.
    db.prepare('UPDATE accounts SET archived = 1 WHERE id = ?').run(clientB);
    const res = await auth(request(app).post('/api/key-forms/generate'))
      .send({ holder: HOLDER, holder_type: 'employee' });
    expect(res.body.forms[0].total_keys).toBe(both - atB);
    expect(res.body.forms[0].clients.some((l: any) => l.account_id === clientB)).toBe(false);
    db.prepare('UPDATE accounts SET archived = 0 WHERE id = ?').run(clientB);
  });

  it('excludes VOIDED custody records', async () => {
    const out = await checkout(clientA, 2);
    await auth(request(app).post(`/api/assignments/${out.body.id}/void`))
      .send({ reason: 'entered in error during testing' });
    const res = await auth(request(app).post('/api/key-forms/generate'))
      .send({ holder: HOLDER, holder_type: 'employee' });
    // A voided record is not custody, so it cannot appear on a custody form.
    // What remains is the standing grid position, which a void never touched.
    expect(res.body.forms[0].total_keys).toBe(gridTotal());
    expect(res.body.forms[0].clients.reduce((n: number, l: any) => n + l.checked_out, 0)).toBe(0);
  });
});

describe('§3 STALENESS IS VISIBLE IF IT EVER RECURS', () => {
  it('stamps every form with when it was made and what it was made from', async () => {
    await checkout(clientA, 2);
    const f = lastForm();
    expect(f.created_at).toBeTruthy();
    // The data-version marker. Two forms carrying the same one must describe
    // the same position — so it is derived from the position itself.
    expect(f.data_version).toMatch(/^v1:[0-9a-f]{16}$/);
    expect(f.data_version).toBe(keyForm.dataVersionFor(keyForm.snapshotHolder(HOLDER, 'employee')));
  });

  it('the marker MOVES when the underlying custody changes', async () => {
    await checkout(clientA, 2);
    const first = lastForm();
    await checkin(clientA, 1);
    const second = lastForm();
    expect(second.data_version).not.toBe(first.data_version);
    expect(second.total_keys).not.toBe(first.total_keys);
  });

  it('keeps the exact PDF against the record, so [View] shows what was sent', async () => {
    await checkout(clientA, 2);
    const f = lastForm();
    expect(f.pdf_path).toBeTruthy();
    expect(fs.existsSync(f.pdf_path)).toBe(true);
    const res = await auth(request(app).get(`/api/key-forms/${f.id}/pdf`));
    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toContain('pdf');
  });

  it('the stored PDF is NOT rebuilt from current state on later views', async () => {
    await checkout(clientA, 2);
    const f = lastForm();
    const at = f.total_keys;
    const firstBytes = fs.readFileSync(f.pdf_path).length;

    // The world moves on.
    await checkin(clientA, 1);
    expect(liveTotal()).toBe(at - 1);

    // Viewing the ORIGINAL must still show what was sent, not today's total.
    const again = one('SELECT * FROM key_form_docs WHERE id = ?', f.id);
    expect(again.total_keys).toBe(at);
    expect(fs.readFileSync(again.pdf_path).length).toBe(firstBytes);
  });
});

describe('§3 REGENERATE — a fresh form supersedes the old one', () => {
  it('produces a new form at the CURRENT position and marks the old superseded', async () => {
    await checkout(clientA, 2);
    const original = lastForm();
    const at = original.total_keys;

    await checkin(clientA, 1);
    // Regenerating the ORIGINAL form, whose numbers are now out of date.
    const res = await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});
    expect(res.status).toBe(201);
    expect(res.body.form.total_keys).toBe(at - 1);
    expect(res.body.form.total_keys).toBe(liveTotal());

    const old = one('SELECT * FROM key_form_docs WHERE id = ?', original.id);
    // The old one stays — superseded, not deleted. It is still what somebody
    // may have signed.
    expect(old.status).toBe('superseded');
    expect(old.superseded_by).toBe(res.body.form.id);
    expect(old.total_keys).toBe(at);
    expect(old.superseded_at).toBeTruthy();

    const fresh = one('SELECT * FROM key_form_docs WHERE id = ?', res.body.form.id);
    expect(fresh.supersedes).toBe(original.id);
  });

  it('records the regeneration and the numbers it changed', async () => {
    await checkout(clientA, 2);
    const original = lastForm();
    const at = original.total_keys;
    await checkin(clientA, 1);
    await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});

    const meta = JSON.parse(one(
      "SELECT metadata FROM audit_log WHERE action='key_form_regenerated' ORDER BY id DESC LIMIT 1"
    ).metadata);
    expect(meta).toMatchObject({
      superseded_form_id: original.id, was_total_keys: at, now_total_keys: at - 1,
    });
    // The marker moved with the numbers.
    expect(meta.was_data_version).not.toBe(meta.now_data_version);
  });

  it('refuses to supersede a SIGNED form', async () => {
    await checkout(clientA, 2);
    const original = lastForm();
    db.prepare("UPDATE key_form_docs SET status='signed', signed_at=? WHERE id=?")
      .run(new Date().toISOString(), original.id);

    const res = await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});
    // A signature is evidence. Replacing the document it attaches to would
    // destroy the stronger record.
    expect(res.status).toBe(409);
    expect(one('SELECT status FROM key_form_docs WHERE id = ?', original.id).status).toBe('signed');
  });

  it('a form already superseded cannot be superseded again', async () => {
    await checkout(clientA, 2);
    const original = lastForm();
    const first = await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});
    expect(first.status).toBe(201);
    const again = await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});
    expect(again.status).toBe(409);
  });

  it('the superseded form still lists, flagged, rather than vanishing', async () => {
    await checkout(clientA, 2);
    const original = lastForm();
    await auth(request(app).post(`/api/key-forms/${original.id}/regenerate`)).send({});
    const list = await auth(request(app).get('/api/key-forms?limit=50'));
    const row = list.body.forms.find((f: any) => f.id === original.id);
    expect(row).toBeTruthy();
    expect(row.status).toBe('superseded');
    expect(row.superseded_by).toBe(
      list.body.forms.find((f: any) => f.supersedes === original.id).id,
    );
  });
});
