import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

interface ContractorSignData {
  contractorName: string;
  contractorEmail: string;
  accounts: string[];
  signatureData: string;
  signedAt: string;
}

export function hashSignature(signatureData: string): string {
  return crypto.createHash('sha256').update(signatureData).digest('hex');
}

export async function generateSignedPDF(data: ContractorSignData): Promise<string> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const { width, height } = page.getSize();

  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await doc.embedFont(StandardFonts.Helvetica);

  const CW_RED = rgb(0.753, 0.153, 0.176);
  const BLACK = rgb(0.102, 0.102, 0.102);
  const GRAY = rgb(0.42, 0.42, 0.408);

  // Header bar
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.102, 0.102, 0.102) });
  page.drawText('City Wide Building Services', {
    x: 40, y: height - 38, size: 18, font: boldFont, color: rgb(1, 1, 1),
  });
  page.drawText('BOSTON — Key Receipt Acknowledgement', {
    x: 40, y: height - 58, size: 11, font: regularFont, color: rgb(0.7, 0.7, 0.7),
  });

  // Red accent line
  page.drawRectangle({ x: 0, y: height - 84, width, height: 4, color: CW_RED });

  let y = height - 110;

  page.drawText('Contractor Agreement', { x: 40, y, size: 16, font: boldFont, color: BLACK });
  y -= 24;
  page.drawText('This document confirms receipt of keys assigned to the contractor listed below.', {
    x: 40, y, size: 10, font: regularFont, color: GRAY,
  });
  y -= 30;

  // Contractor details
  page.drawText('Contractor Name:', { x: 40, y, size: 10, font: boldFont, color: BLACK });
  page.drawText(data.contractorName, { x: 160, y, size: 10, font: regularFont, color: BLACK });
  y -= 18;
  page.drawText('Email:', { x: 40, y, size: 10, font: boldFont, color: BLACK });
  page.drawText(data.contractorEmail, { x: 160, y, size: 10, font: regularFont, color: BLACK });
  y -= 18;
  page.drawText('Signed At:', { x: 40, y, size: 10, font: boldFont, color: BLACK });
  page.drawText(new Date(data.signedAt).toLocaleString('en-US', { timeZone: 'America/New_York' }), {
    x: 160, y, size: 10, font: regularFont, color: BLACK,
  });
  y -= 30;

  // Assigned accounts
  page.drawRectangle({ x: 40, y: y - 4, width: width - 80, height: 20, color: rgb(0.95, 0.95, 0.95) });
  page.drawText('ASSIGNED ACCOUNTS', {
    x: 44, y: y + 2, size: 10, font: boldFont, color: BLACK,
  });
  y -= 20;

  for (const account of data.accounts) {
    if (y < 120) {
      const newPage = doc.addPage([612, 792]);
      y = newPage.getSize().height - 60;
    }
    page.drawText(`• ${account}`, { x: 52, y, size: 10, font: regularFont, color: BLACK });
    y -= 16;
  }

  y -= 20;

  // Agreement text
  const agreementLines = [
    'I, the undersigned contractor, acknowledge that I have received the keys listed above',
    'and agree to: (1) safeguard all keys and access credentials, (2) not duplicate or share',
    'keys with unauthorized personnel, (3) return all keys immediately upon request or contract',
    'termination, and (4) report any lost or stolen keys to City Wide Boston within 24 hours.',
  ];
  for (const line of agreementLines) {
    page.drawText(line, { x: 40, y, size: 9, font: regularFont, color: GRAY });
    y -= 14;
  }

  y -= 20;

  // Signature
  if (data.signatureData && data.signatureData.startsWith('data:image/png;base64,')) {
    const base64 = data.signatureData.replace('data:image/png;base64,', '');
    const imgBytes = Buffer.from(base64, 'base64');
    const img = await doc.embedPng(imgBytes);
    const imgDims = img.scale(0.4);
    page.drawRectangle({
      x: 40, y: y - imgDims.height - 4,
      width: imgDims.width + 8, height: imgDims.height + 8,
      borderColor: rgb(0.88, 0.88, 0.867), borderWidth: 1,
    });
    page.drawImage(img, { x: 44, y: y - imgDims.height, width: imgDims.width, height: imgDims.height });
    y -= imgDims.height + 14;
  }

  page.drawLine({ start: { x: 40, y }, end: { x: 280, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 14;
  page.drawText(`${data.contractorName} — Electronic Signature`, {
    x: 40, y, size: 9, font: regularFont, color: GRAY,
  });

  // Footer
  const hash = hashSignature(data.signatureData);
  page.drawText(`SHA-256: ${hash.slice(0, 32)}...`, {
    x: 40, y: 30, size: 7, font: regularFont, color: rgb(0.7, 0.7, 0.7),
  });
  page.drawText('City Wide Building Services · Boston, MA · Generated by Key Management System', {
    x: 40, y: 18, size: 7, font: regularFont, color: rgb(0.7, 0.7, 0.7),
  });

  const pdfBytes = await doc.save();
  const uploadsDir = path.join(__dirname, '../../uploads/signatures');
  if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
  const fileName = `contractor_${Date.now()}_${data.contractorName.replace(/\s+/g, '_')}.pdf`;
  const filePath = path.join(uploadsDir, fileName);
  fs.writeFileSync(filePath, pdfBytes);
  return filePath;
}
